name: Minishell CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  norminette:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
    - name: Install norminette
      run: python3 -m pip install norminette
    - name: Running Norminette
      run: norminette sources includes | grep "Error!" && exit 1 || exit 0

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libreadline-dev
    - name: Building Binary
      run: make

  unit_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libreadline-dev
    - name: Running Unit Tests
      run: make test

  integration_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libreadline-dev
    - name: Running Integration Tests
      run: make test_integration

  valgrind:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libreadline-dev valgrind
    - name: Build Tests
      run: |
        make -s test
